[general]
fontname=Hack 11
selbg=#00ffff
selfg=#000000
color_preset=Tango
bgcolor=#0a0a0a
bgalpha=65535
fgcolor=#aaaaaa
cursorblinks=true
cursorunderline=false
audiblebell=false
tabpos=top
hide_menubar=true
hide_scrollbar=true
disable_f10=true
