#!/bin/sh
set -e

lb config noauto \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --mode debian \
  --distribution bookworm \
  --debian-installer false \
  --archive-areas "main contrib" \
  --bootappend-live "boot=live components console=tty0 username=live quiet splash init=/lib/systemd/systemd live-noconfig" \
  --bootloader grub \
  --security false \
  --apt-indices false \
  --firmware-chroot false \
  --firmware-binary false \
  "${@}"
