#!/bin/sh
set -e

lb config noauto \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --mode debian \
  --distribution bookworm \
  --debian-installer false \
  --archive-areas "main contrib" \
  --bootappend-live "boot=live components quiet splash console=tty0" \
  --bootloader grub \
  --security false \
  --apt-indices false \
  "${@}"
